### ISSUE TITLE
[New App Shortcut]: RaiPlay (IT)

### ISSUE THREAD

**Issue by berta17** [PRProd/HA-Firemote#35]
### App Name

RaiPlay

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Italian public television

**Comment by PRProd** [comment]
Version [1.11.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.1) has been released and it contains your requested app shortcut addition.  Since the app is not officially available in my region, please let me know right away if this shortcut does not work as intended.

Thanks for your contribution!

**Comment by berta17** [comment]
Does not work. If you need more info just let me know.
Other commands and the shortcuts I tried works correctly.

Thank you very much!

**Comment by PRProd** [comment]
Sorry about that!  It's tough when I can't actually test it on my end, so I appreciate your patience and willingness to work with me.

If you're able to [follow the instructions here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests), that would go a long way in helping me make this work for you.

Thanks!

**Comment by berta17** [comment]
I followed the instructions for the App Requests. The output is:
`adb_response: mSurface=Surface(name=it.rainet.androidtv/it.rainet.androidtv.ui.PlayerActivity)
      mSurface=Surface(name=SurfaceView)
  mCurrentFocus=Window{255e515d u0 it.rainet.androidtv/it.rainet.androidtv.ui.PlayerActivity}
  mFocusedApp=AppWindowToken{12ec2bb3 token=Token{3e1d3522 ActivityRecord{f55d2ed u0 it.rainet.androidtv/.ui.PlayerActivity t212}}}
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_1_105?token=6a98239d7e9a1fd35900bbac2e143d0b5d1400e150a2d2d0e90a4cee0c2dcb5f&cache=1676061433.974275
friendly_name: FireTV
supported_features: 22961
source_list: Netflix, it.rainet.androidtv
app_id: it.rainet.androidtv
source: it.rainet.androidtv`

**Comment by PRProd** [comment]
@berta17 - Thank you for that information!  I've released version [v1.11.2](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.2) which should contain the fix.

**Comment by berta17** [comment]
Thank you for the effort, sadly it still doesn't work. Is there something more that I can do to help fix it?

**Comment by PRProd** [comment]
It's possible that there is a Home Assistant cache issue with the device that you are using.  If clearing your cache doesn't help, I would suggest restarting your home assistant instance.  If that doesn't work, then I suggest uninstalling Firemote (through HACS) and re-installing it.  I'm 98% percent sure that one of those ideas will be helpful.

**Comment by berta17** [comment]
Tried to all the above ideas, I also tried to uncouple the firetv itself and integrate back to home assistant. None of them worked.
All the other commands and apps works, RAIPlay does not lauch with the dedicated button. 
I noticed that if I lauch the app manually, the button correcly lights up.

**Comment by PRProd** [comment]
This is puzzling... Out of curiosity, what kind of Fire TV device do you have?

Let's try something else.  What happens when you run the following command in the Developer Tools?  
`adb shell am start -n it.rainet.androidtv/.ui.PlayerActivity`

Does the RaiPlay app launch on your Fire TV?  If not, do any ADB errors appear in the States tab?

![image](https://user-images.githubusercontent.com/25486599/219823937-7a40142c-f258-4a2c-b0d3-32c35ddb988e.png)

**Comment by berta17** [comment]
The command does not lauch the app properly: the screen goes black and stays black until I press home to come back.
No errors in the states tab.

The black screen happens only with the command, not with pressing the button on the card

**Comment by PRProd** [comment]
@berta17  - 2 Important questions for you

1. What kind of Amazon Fire TV Device do you have?  ([please choose from this list](https://github.com/PRProd/HA-Firemote/wiki/Existing-Amazon-Devices---Support-Chart))
2. Are you running the latest, most up to date version of the RaiPlay IT app?  Last updated Jan 25, 2023

**Comment by berta17** [comment]
I just realized that this is a Fire TV Stick - Basic Edition.
I am running the latest version of the app

**Comment by PRProd** [comment]
@berta17 - The Fire TV Stick Basic Edition is one that I haven't been able to get my hands on yet, which is why it is not on the official support list.  It would really help me out if you are willing to open a [Device Support Request](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=New+Device+Support%2Cenhancement&template=device_support_request.yaml&title=%5BNew+Device+Support%5D%3A+%20Fire%20TV%20Stick%20-%20Basic%20Edition) issue, and you are able to fill out the entire form, especially the **Interrogation ADB Response** section.  The interrogation info is extremely useful.

As far as the RaiPlay app, I'm kind of at a loss right now.  Since I'm unable to download it through the Amazon Fire App Store in the US, I had to search for it in other places.  The latest version I could find is named `it.rainet`, but it seems that the one you have is named `it.rainet.androidtv`.  Would you be willing to try to delete the app from your firestick, restart your firestick, and then use the firestick's built in "Get More Apps" feature to find and re-install it?  Id be interested to know if the results of [this test](https://github.com/PRProd/HA-Firemote/issues/35#issuecomment-1423337637) are different than [the ones you had before](https://github.com/PRProd/HA-Firemote/issues/35#issuecomment-1426319586).

As always, I sincerely appreciate your willingness to work this out with me!  I don't want to give up!

**Comment by berta17** [comment]
Thank you very much for the help.
I opened a Device Support Request with the output data needed.

I tried to follow the reinstallation procedure, the output is:
`source_list: it.rainet.androidtv
app_id: it.rainet.androidtv
source: it.rainet.androidtv
adb_response: mSurface=Surface(name=it.rainet.androidtv/it.rainet.androidtv.ui.MainLeanbackActivity)
  mCurrentFocus=Window{2e5611c2 u0 it.rainet.androidtv/it.rainet.androidtv.ui.MainLeanbackActivity}
  mFocusedApp=null
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_1_116?
friendly_name: Fire TV 192.168.1.116
supported_features: 22961`

**Comment by PRProd** [comment]
@berta17 - Between your last message and my recent acquisition of an NVIDIA Shield Pro Android Device using an Italian proxy server, I have made (hopefully) one last update which should fix the button!  I can verify that this works on my end.  

Please update your Firemote card to the latest version [v1.11.4](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.4) and hopefully share with me some good news!   :smiley:

**Comment by berta17** [comment]
Finally it works. Thank you very much again.
